authoris/authoris/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userlist/', include('userlist.urls', namespace='userlist')),
    path('', RedirectView.as_view(url='/userlist/'), name='index'),
]

authoris/userlist/urls.py
from django.urls import path , include
from . import views
from rest_framework.routers import DefaultRouter
from django.contrib.auth import views as auth_views
from .views import UserViewSet,AuthView

router = DefaultRouter()
router.register(r'users', UserViewSet)

app_name = 'userlist'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('home/', views.home, name='home'),
    path('api/', include(router.urls)),  # Включение маршрутов API
    path('api/u/email/', views.UserDetailByEmail.as_view(), name='user-detail-by-email'), # получение пользователя по email
    path('api/auth/', AuthView.as_view(), name='auth'),
]

authoris/userlist/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class Users(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class users_AuthLog (models.Model):
    users = models.ForeignKey(Users, on_delete=models.CASCADE) 
    timestamp = models.DateTimeField(auto_now_add=True)
    event_type = models.CharField(max_length=10, choices=[('login','Login'),('logout','Logout')])
    ip_address = models.GenericIPAddressField()
    user_browser = models.TextField()
    success = models.BooleanField(default=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return f"{self.user.email} - {self.event_type} at {self.timestamp}"

authoris/userlist/forms.py
from django import forms
from .models import Users

class LoginForm(forms.Form):
    email = forms.EmailField()  # Поле для email
    password = forms.CharField(widget=forms.PasswordInput)  # Поле для пароля

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = Users
        fields = ['email', 'password', 'password_confirm']

    def clean_password_confirm(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password_confirm']:  # Исправлено на password_confirm
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password_confirm']  # Исправлено на password_confirm
    

authoris/userlist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserRegistrationForm , LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model, authenticate,login
from django.contrib import messages
from rest_framework import viewsets,generics, status
from rest_framework.response import Response
from .serializers import UserSerializer
from .models import Users
from rest_framework.views import APIView

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    queryset = Users.objects.all()
    serializer_class = UserSerializer

class UserDetailByEmail(generics.RetrieveAPIView):
    serializer_class = UserSerializer

    def get(self, request, *args, **kwargs):
        print("UserDetailByEmail.get called")  # Логируем вызов метода
        email = request.query_params.get('email', None)  # Получаем email из параметров запроса
        print(f"Received email: {email}")  # Логируем полученный email
        if email is not None:
            try:
                user = Users.objects.get(email=email)  # Ищем пользователя по email
                serializer = self.get_serializer(user)
                return Response(serializer.data)  # Возвращаем данные пользователя
            except Users.DoesNotExist:
                return Response({"detail": "User not found."}, status=status.HTTP_404_NOT_FOUND)
        return Response({"detail": "Email parameter is required."}, status=status.HTTP_400_BAD_REQUEST)

class AuthView(APIView): # апи аутентификация 
    def post(self, request):
        email = request.data.get("email")
        password = request.data.get("password")
        
        user = authenticate(request, email=email, password=password)
        
        if user is not None:
            return Response({"message": "Authentication successful", "user": {"email": user.email}}, status=status.HTTP_200_OK)
        else:
            return Response({"detail": "Invalid credentials"}, status=status.HTTP_401_UNAUTHORIZED)


def index(request):
    return render(request, 'userlist/index.html')

def home(request):
    return render(request, 'userlist/home.html')

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None and user.is_active:
                login(request, user)
                return redirect('userlist:home')
            else:
                if user is None:
                    form.add_error(None, 'Неверный логин или пароль.')
                elif not user.is_active:
                    form.add_error(None, 'Ваш аккаунт неактивен.')
                    print(form.non_field_errors)
    else:
        form = LoginForm()
    return render(request, 'userlist/login.html', {'form': form})




def user_list(request):
    users = User.objects.all()
    return render(request, 'userlist/user_list.html', {'users': users})

from django.http import JsonResponse
from .forms import UserRegistrationForm

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Создаем новый объект пользователя, но не сохраняем его сразу
            new_user = user_form.save(commit=False)
            # Устанавливаем выбранный пароль
            new_user.set_password(user_form.cleaned_data['password'])
            # Сохраняем объект пользователя
            new_user.save()
            
            login(request, new_user)
            # Возвращаем JSON-ответ
            return JsonResponse({'success': True, 'message': 'Регистрация успешна!', 'redirect_url': '/userlist/home'})
        else:
            # Возвращаем ошибки валидации в JSON-формате
            return JsonResponse({'success': False, 'errors': user_form.errors}, status=400)
    else:
        user_form = UserRegistrationForm()
    return render(request, 'userlist/register.html', {'user_form': user_form})

authoris/userlist/templates/userlist/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'userlist/css/styles.css' %}">
    <title>{% block title %} Virtual Pretty Network {% endblock %}</title>
</head>
<body id="content">

    {% block content %}
    {% endblock %}
    <!-- <script src="{% static 'userlist/js/animate_header.js' %}"></script> -->
    <script src="{% static 'userlist/js/modal.js' %}"></script>
</body>
</html>

authoris/userlist/templates/userlist/home.html
{% extends "userlist/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>Welcome to the Home Page!</h1>
    <p>Hello, {{ user.email }}!</p>
    <form method="post" action="{% url 'userlist:logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

authoris/userlist/templates/userlist/index.html
{% extends 'userlist/base.html' %}

{% block content %}
<header class="header">
  <div class="div-header">
    <a class="first-item"></a>
    <div>
      <nav>
        <ul>
          <!--  -->
          <li> 
            <button >
              <h1 class="hover-header-elem"> Преимущества Pretty VPN</h1>  
            </button>
          </li>
          <li class="li-prices">
            <h1 class="hover-header-elem">Цены</h1>
          </li>
          <li>
            <h1 class="hover-header-elem">Скачать</h1>
          </li>
          <li>
            <h1 class="hover-header-elem"><a href="#" id="openModal" data-url="{% url 'userlist:register' %}">Регистрация</a></h1>
          </li>
          <li>
            <h1 class="hover-header-elem"><a href="{% url 'userlist:login' %}">Вход</a></h1>
          </li>
          <!--  -->
        </ul>
      </nav>
    </div>
  </div>
</header>  
<section class="sec-pass">
  <div>
    контент текстом  
  </div>
  <div>
    какая-то картинка 
  </div>
</section>


<!-- Модальное окно -->
<div id="registrationModal" class="modal">
  <div class="modal-content">
      <span class="close">&times;</span>
      <h2>Регистрация</h2>
      <div id="modalFormContent">
          <!-- Здесь будет загружена форма регистрации -->
      </div>
  </div>
</div>
{% endblock %}

authoris/userlist/templates/userlist/login.html
{% extends "userlist/base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    


    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

authoris/userlist/templates/userlist/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
{{ post.body|linebreaks }}
{% endblock %}

authoris/userlist/templates/userlist/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}

authoris/userlist/templates/userlist/register.html
{% extends "userlist/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Создать аккаунт</h1>
    <p>Введите почту и придумайте пароль</p>
    <form id="registrationForm" action="." method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ user_form.email }}  <!-- Изменено на user_form -->
        </div>
        <div class="form-group">
            <label for="id_password">Password:</label>
            {{ user_form.password }}  <!-- Изменено на user_form -->
        </div>
        <div class="form-group">
            <label for="id_password_confirm">Confirm Password:</label>
            {{ user_form.password_confirm }}  <!-- Изменено на user_form -->
        </div>
        <button type="submit">Register</button>
    </form>
{% endblock %}

authoris/userlist/templates/userlist/register_done.html
{% extends "userlist/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
    <p>Your account has been successfully created. Your username is: <strong>{{ usermail }}</strong>.
        Now you can <a href="{% url "login" %}?username={{ username }}">log in</a>.</p>
{% endblock %}

authoris/userlist/templates/userlist/user_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/styles.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>